---
title: "彭博tf-idf"
author: "Viviantsui0514"
date: "2018年4月3日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#彭博tf-idf

##FB API
>彭博商業週刊粉專
```{r}
library(Rfacebook)
token <- "EAACEdEose0cBADSZCqNxjLETepd1kEZAfHvwwY37BQ6qQGYpqKGTKi6hIXul9ZCTzPvdbQgHIrsbfzOZB9SRayvjbmQyoHm5GftnnS684NZAzU7froCe0QYt3Rn5uuuZAIFc2YGiJNrS8ZBczBbPfH3ZALGAXuPahi64j8YEUKFwcZAn47uDZCPRpdxNnNhGKPgWw7TanHJ6sTIgZDZD"
me <- getUsers("me", token, private_info = TRUE)
me$name
page.id <- "214578858689103" 
page <- getPage(page.id, token=token, n = 100)
str(page)
```

```{r}
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(slam)
library(RColorBrewer)
library(wordcloud)

docs <- Corpus(VectorSource(page$message))
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))}
)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
mixseg <- worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
```
* [如何解決 rJava 無法正常載入問題](http://earthworm2016.pixnet.net/blog/post/323353783-%5Br%5D-%E5%A6%82%E4%BD%95%E8%A7%A3%E6%B1%BA-rjava-%E7%84%A1%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%BC%89%E5%85%A5%E5%95%8F%E9%A1%8C)
* [如何解決 Rwordseg 無法正常載入問題](https://blog.csdn.net/sinat_26917383/article/details/50867851)
```{r}

Sys.setenv(JAVA_HOME = "C:/Program Files/Java/jre-10")
library(rJava)
library(Rwordseg)
library(tmcn)  
library(rjson)
seg <- lapply(docs, jieba_tokenizer)
freqFrame <- as.data.frame(table(unlist(seg)))
freqFrame <- freqFrame[-c(1:34),]
tail(freqFrame)
```

##建立詞頻矩陣
```{r}
d.corpus <- Corpus(VectorSource(seg))
tdm <- TermDocumentMatrix(d.corpus, control = list(wordLengths = c(2, Inf)))
inspect(tdm)
```

##建立tf-idf
```{r}
library(SnowballC)
library(slam)
library(Matrix)
N = tdm$ncol
tf <- apply(tdm, 2, sum)
idfCal <- function(word_doc)
{
  log2( N / nnzero(word_doc) )
}
idf <- apply(tdm, 1, idfCal)

doc.tfidf <- as.matrix(tdm)
for(x in 1:nrow(tdm))
{
  for(y in 1:ncol(tdm))
  {
    doc.tfidf[x,y] <- (doc.tfidf[x,y] / tf[y]) * idf[x]
  }
}

tail(doc.tfidf)


```

