---
title: "Project4"
author: "Viviantsui0514"
date: "2018年5月20日"
output: html_document
---
# Apriori Algorithm

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Package
```{r}
library(plyr)
library(dplyr)
library(tidyr)
library(arules)
library(arulesViz)
```

## Kaggle's data

> Data from competition [Instacart Market Basket Analysis](https://www.kaggle.com/c/instacart-market-basket-analysis/kernels)

```{r}
library(data.table)
path <- "C:\\Users\\vivian\\Desktop\\Rcourse2018\\Project2 Kaggle"

aisles <- fread(file.path(path, "aisles.csv"))
departments <- fread(file.path(path, "departments.csv"))
orderp <- fread(file.path(path, "order_products__prior.csv"))
ordert <- fread(file.path(path, "order_products__train.csv"))
products <- fread(file.path(path, "products.csv"))
```


## Arranging data
```{r}
products <- products %>% inner_join(aisles) %>% inner_join(departments) %>% select(-aisle_id,-department_id)

rm(aisles,departments)
```

```{r}
orderp <- orderp %>% select(order_id,product_id) %>% left_join(products)
ordert <- ordert %>% select(order_id,product_id) %>% left_join(products)
orderpt <- rbind(orderp,ordert) 

rm(ordert,orderp,products)
gc()
```

```{r}
orderpt <- orderpt %>% select(order_id,aisle)
samplenumber <- sample(unique(orderpt$order_id),50000)
sampleorder <- filter(orderpt,order_id %in% samplenumber)
rm(orderpt)
```

## Applying Model
```{r}
trans <- as(split(sampleorder[,"aisle"], sampleorder[,"order_id"]), "transactions")
itemFrequencyPlot(trans, support=0.15)
basket_rules <- apriori(trans,
                        parameter = list(sup = 0.1, conf = 0.5,target="rules",minlen = 2))

inspect(sort(basket_rules,by = 'lift'))
rulesort <- sort(basket_rules,by = 'lift')[1:20]
```
## Visualization
```{r}
library(arulesViz)
plot(rulesort)

plot(rulesort,method="grouped") 

plot(rulesort,method="graph",control=list(type="items"))

plot(rulesort,method = "paracoord",control = list(reorder = TRUE))
```
