---
title: "Basic data visualization"
author: "Viviantsui0514"
date: "2018年3月20日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Base Plotting System
```{r}
require(datasets)
head(airquality)
```

## ‧hist()
>直方圖(Histogram)
```{r}
hist(x=airquality$Month, 
     main="Histogram of Month",  
     xlab="Month",               
     ylab="Frequency")                
```

## ‧boxplot()
>盒鬚圖(Box Plot)
```{r}
boxplot(formula = Ozone ~ Month, # Y ~ X 
        data = airquality,       
        xlab = "Month",          
        ylab = "Ozone (ppb)",    
        col ="gray")        
```

## ‧plot()
>散布圖(Scatter Plot)
```{r}
plot(x=airquality$Month,            
     y=airquality$Temp,             
     main="Month to Temperature",   
     xlab="Month(1~12)",            
     ylab="Temperature(degrees F)")      
```

## ‧Two stage
1. Creation of a plot
2. Annotation of a plot
```{r}
##stage 1
plot(x=airquality$Ozone,
     y=airquality$Wind,
     main="Ozone to Wind",
     xlab="Ozone(ppb)",
     ylab="Wind(mph)",
     pch=16      #point shape            
) 

# stage 2
May_data <- airquality[airquality$Month==5, ] 
points(x=May_data$Ozone,                       
       y=May_data$Wind, 
       pch=16,                  
       col="blue")              

Aug_data <- airquality[airquality$Month==8, ]   
points(x=Aug_data$Ozone, 
       y=Aug_data$Wind, 
       pch=16,               
       col="red")           


legend("topright",                            
       pch = 1,                                
       col = c("blue", "red", "black"),           
       legend = c("May", "August", "Other Month")
       )


lm.model <- lm(Wind~Ozone, airquality)    
abline(lm.model,                          
       lwd=2) 

```

## ‧par()
```{r}
par(mfrow = c(1,2)) 
# first
plot(airquality$Wind, airquality$Ozone, main = "Wind to Ozone") 
# second
plot(airquality$Solar.R, airquality$Ozone, main = "Solar.R to Ozone")
```
