---
title: "台灣M1B和M2"
author: "Viviantsui0514"
date: "2018年4月2日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


>結合**R的ggplot2**和**貨幣銀行學**知識, 觀察台灣M1B和M2

* 資料來源: [中央銀行統計資料庫](https://www.cbc.gov.tw/CPX/Tree/TreeSelect#Content)

##匯入資料
```{r}
library(readr)
m<- read_csv("C:/Users/vivian/Desktop/Rcourse2018/Week3/Monetary/EF17Y01.csv")
library(plotly)
library(ggplot2)
```

##**台灣M1B和M2原始值**
* [如何在ggplot2上畫兩條線](https://blog.gtwang.org/r/r-data-exploration-and-visualization/3/)
* [如何在ggplot2上畫兩條不同顏色的線](http://yjliu.net/notes/2013/01/19/ggplot2-plot-2-lines-in-same-graph.html)
```{r}
a <- ggplot(m, aes(x = m$期間)) + geom_point(aes(y = m$`貨幣總計數-Ｍ１Ｂ-原始值`),color = "orange") + geom_point(aes(y = m $`貨幣總計數-Ｍ２-原始值`), color = "blue") + theme_bw()


ggplotly(a) %>%
  layout(
    title = "台灣M1B和M2原始值 ",
    yaxis = list(
      title = "原始值(M1B:橘,M2:藍)",
      zeroline = F,
      tickprefix = F
    ),
    xaxis = list(
      title = "日期",
      zeroline = F, 
      showgrid = F
    )
  ) 
```

###觀察
* M1B數量始終小於M2 (原因: M2 = M1B + 準貨幣)

##**台灣M1B與M2年增率**
```{r}
b <- ggplot(m, aes(x = m$期間)) + geom_line(aes(y = m$`貨幣總計數-Ｍ１Ｂ-年增率`), color = "orange") + geom_line(aes(y = m$`貨幣總計數-Ｍ２-年增率`), color = "blue") + theme_classic()

ggplotly(b) %>%
  layout(
    title = "台灣M1B與M2年增率 ",
    yaxis = list(
      title = "年增率(M1B:橘,M2:藍)",
      zeroline = F,
      tickprefix = F
    ),
    xaxis = list(
      title = "日期",
      zeroline = F, 
      showgrid = F
    )
  ) 
```

###觀察
* M1B年增率波動幅度大於M2
* M1B年增率最高點:2009(適逢台灣股房兩市暴漲時期)